---
title: thread-interrupt
date: 2022-10-18 16:14:52
tags: Java 多线程
categories: Java多线程
---

线程的stop等方法都被废弃了。在一些场景下，我们可以通过让线程中断的方式结束掉线程。

首先抛出2个问题：

1. synchronized加锁的线程可以被中断吗？
2. ReentrantLock加锁可以被中断吗？

回答上面的问题，先看看2个小示例：

## [](#synchronized加锁是否可以中断)synchronized加锁是否可以中断

```
/** * @author javaer * @Description * @create 2022-09-28 10:56 */
@Slf4j
public class SyncInterrupt {
    @SneakyThrows
    public static void main(String[] args) {
        Object o = new Object();

        Thread t1 = new Thread(() -> {            synchronized (o) {                log.debug("thread start ~~");                while (Thread.currentThread().isInterrupted()) {                    break;                }            }            log.debug("thread over~");        }, "t1");        t1.start();        synchronized (o) {            Thread.sleep(1000);            log.debug("main  interrupt t1 thread");            t1.interrupt();            t1.join();        }    }}
```

输出：

```
18:26:34.169 [main] DEBUG com.demo.SyncInterrupt - main  interrupt t1 thread
```

这说明主线程抢占锁后，中断t1线程并等待t1执行完毕。t1无法响应中断

## [](#reentrantlock加锁是否可以中断)ReentrantLock加锁是否可以中断

```
**
 * @author javaer
 * @Description
 * @create 2022-09-28 18:28
 */
@Slf4j
public class ReetInterrupt {

    @SneakyThrows
    public static void main(String[] args) {
        ReentrantLock lock = new ReentrantLock();
        Thread t1 = new Thread(() -> {            try {                lock.lock();                log.debug("thread start ~~");                while (Thread.currentThread().isInterrupted()) {                    break;                }                log.debug("thread over~");            }  finally {                lock.unlock();            }        }, "t1");        t1.start();        lock.lock();        try {            Thread.sleep(1000);            log.debug("main  interrupt t1 thread");            t1.interrupt();            t1.join();        } finally {            lock.unlock();        }    }}
```

输出：

```
18:35:25.735 [main] DEBUG com.demo.ReetInterrupt - main  interrupt t1 thread
```

说明ReentrantLock.lock 方法不支持打断。如果要打断，应该使用lockInterruptibly方法。

将上面demo 改造以下，通过lockInterruptibly方法加锁

```
/** * @author javaer * @Description * @create 2022-09-28 18:28 */
@Slf4j
public class ReetInterrupt {

    @SneakyThrows
    public static void main(String[] args) {
        ReentrantLock lock = new ReentrantLock();
        Thread t1 = new Thread(() -> {            try {                lock.lockInterruptibly();                log.debug("thread start ~~");                while (Thread.currentThread().isInterrupted()) {                    break;                }                log.debug("thread over~");            } catch (InterruptedException e) {                log.error("exception :", e);            } finally {                lock.unlock();            }        }, "t1");        t1.start();        lock.lock();        try {            Thread.sleep(1000);            log.debug("main  interrupt t1 thread");            t1.interrupt();            t1.join();        } finally {            lock.unlock();        }    }}
```

输出：

```
18:36:49.028 [main] DEBUG com.demo.ReetInterrupt - main  interrupt t1 thread
18:36:49.031 [t1] ERROR com.demo.ReetInterrupt - exception :
java.lang.InterruptedException: null
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireInterruptibly(AbstractQueuedSynchronizer.java:898)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1222)
    at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
    at com.demo.ReetInterrupt.lambda$main$0(ReetInterrupt.java:21)
    at java.lang.Thread.run(Thread.java:748)
Exception in thread "t1" java.lang.IllegalMonitorStateException
    at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
    at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
    at com.demo.ReetInterrupt.lambda$main$0(ReetInterrupt.java:30)
    at java.lang.Thread.run(Thread.java:748)
```

> 在非登场场景下，如ReentrantLock\synchronized 已经进入到临界区内，那么也是也响应的

# [](#jdk相关api)JDK相关API

- Thread.interrupted() 判断线程是否被打断。它会清楚线程的打断状态
- interrupt 打断线程
- isInterrupted 返回线程的打断状态

看看如下代码输出：

```
@Slf4j
public class Interrupted {
    public static void main(String[] args) {
        System.out.println(Thread.currentThread().isInterrupted());
        Thread.currentThread().interrupt();
        log.debug("Thread.interrupted result--: "+Thread.interrupted());
        System.out.println(Thread.currentThread().isInterrupted());
        System.out.println(Thread.currentThread().isInterrupted());

    }
}
```

输出：

```
false
18:42:45.026 [main] DEBUG com.demo.Interrupted - Thread.interrupted result--: true
false
```

通过interrupt打断后，在通过log.debug中调用interrupted后，线程打断状态输出的是false

总结： 如果想打断线程，最好使用ReentrantLock的lockInterruptibly方法。在等锁状态下ReentrantLock与synchronized 都不可被打断。
